-- =============================================
-- MODULO INTERBANCARIO SWIFT - POSTGRESQL
-- Ejecutar solo si ya existe el schema base.
-- Para una instalacion completa en Railway use schema_postgres.sql.
-- =============================================

CREATE TABLE IF NOT EXISTS bancos_externos (
    id_banco_externo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    swift VARCHAR(20) NOT NULL UNIQUE,
    base_url VARCHAR(255) NOT NULL,
    endpoint_validacion VARCHAR(255) NOT NULL DEFAULT '/api/transferencia/validar',
    endpoint_transferencia VARCHAR(255) NOT NULL DEFAULT '/api/transferencias/interbancaria/entrante',
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transferencias_interbancarias (
    id_transferencia_interbancaria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('SALIENTE', 'ENTRANTE')),
    id_cuenta_origen INTEGER NULL REFERENCES cuenta(id_cuenta) ON DELETE SET NULL,
    numero_cuenta_origen VARCHAR(30) NULL,
    id_cuenta_destino INTEGER NULL REFERENCES cuenta(id_cuenta) ON DELETE SET NULL,
    numero_cuenta_destino VARCHAR(30) NULL,
    banco_origen_swift VARCHAR(20) NULL,
    banco_destino_swift VARCHAR(20) NULL,
    banco_destino_nombre VARCHAR(150) NULL,
    monto NUMERIC(15,2) NOT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'GTQ',
    descripcion TEXT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'RECHAZADA', 'ERROR')),
    referencia_interna VARCHAR(80) NOT NULL UNIQUE,
    referencia_externa VARCHAR(150) NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    id_movimiento INTEGER NULL REFERENCES movimiento(id_movimiento) ON DELETE SET NULL,
    request_payload TEXT NULL,
    response_payload TEXT NULL,
    error_mensaje TEXT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_inter_tipo_idempotency UNIQUE (tipo, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_inter_estado ON transferencias_interbancarias (estado);
CREATE INDEX IF NOT EXISTS idx_inter_swift_destino ON transferencias_interbancarias (banco_destino_swift);
CREATE INDEX IF NOT EXISTS idx_inter_swift_origen ON transferencias_interbancarias (banco_origen_swift);

CREATE TABLE IF NOT EXISTS api_keys_bancos (
    id_api_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_banco_externo INTEGER NULL REFERENCES bancos_externos(id_banco_externo) ON DELETE SET NULL,
    nombre VARCHAR(150) NOT NULL,
    api_key_hash CHAR(64) NOT NULL UNIQUE,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ejemplo para registrar un banco externo:
-- INSERT INTO bancos_externos
-- (nombre, swift, base_url, endpoint_validacion, endpoint_transferencia, activo)
-- VALUES
-- ('Banco Demo', 'DEMOGTGC', 'https://banco-demo.up.railway.app',
--  '/api/transferencia/validar', '/api/transferencias/interbancaria/entrante', TRUE);

-- Ejemplo para registrar una API key entrante:
-- Guardar SHA256 de la clave, no la clave en texto plano.
-- INSERT INTO api_keys_bancos (id_banco_externo, nombre, api_key_hash)
-- VALUES (1, 'Banco Demo Key', encode(digest('clave-secreta-compartida', 'sha256'), 'hex'));
-- Requiere la extension pgcrypto si desea calcular el hash dentro de PostgreSQL.
